lib/create-common-client.js

- Allows the user to specify an 'options' property.
- Add a clustered index to schemaversion which is required for Azure SQL.

Add support for Azure SQL.

---

lib/create-common-client.js

We are using timestamps generated by [moment](https://github.com/moment/moment/) and ran into an arithmetic overflow trying to store a typical timestamp. For example, this:
```js
var timestamp = moment.utc().valueOf();
console.log(timestamp);
-- 1434398370040
```
This value cannot be stored as INT.  This PR changes the data type of the column to BIGINT, which works fine.
I looked through the tests, and wasn't sure how you wanted this tested.  Let me know if I need to do anything further to help with this.

Increase version data type to accomodate large timestamps

---

package.json
postgrator.js
readme.md

Line feeds: Unix/Mac uses LF, Windows uses 'CRLF', this causes problems for postgrator when calculating the md5 checksum of the migration files - particularly if some developers are on windows, some are on mac, etc. To negate this, you can use the `newline` config flag to tell postgrator to always use a particular line feed, e.g.
```
postgrator.setConfig({
migrationDirectory: __dirname + '/migrations', 
driver: 'pg', // or pg.js, mysql, mssql, tedious
host: '127.0.0.1',
database: 'databasename',
username: 'username',
password: 'password',
newline: 'CRLF'
});
```

Cross platform consistent md5 checksum support

---

lib/create-common-client.js
postgrator.js
readme.md

I need to manage multiple components in the same application that have their own migration paths, but the limitation of a single schemaversion table gets in the way.
The simplest way to implement this would be to make it configurable so I could use different tables for this, which is what I ended up doing.
One note though: I wanted to write some tests for this, but the default test connection is using an amazon aws instance of postgres, which I seem to have left in a broken state by stopping a test half-way.
Is there a reason for the aws instance being used? Otherwise, I think we should move to travis-ci and localhost for testing instead.

Configure schema table

---

postgrator.js

Added a getVersions function which returns an object with the current applied schema version and the max schema version available. This will make it easier to check if the schema is correct on different environments.
Thank you!

Added getVersions

---

postgrator.js

If schemaversion table is modified manually, or corrupted, we should add a check of retrieved lines

Fix an issue with a migration exception

---

lib/create-common-client.js
readme.md

The request timeout was hardcoded as one hour for mssql connections.
This change makes this option configurable if the user wishes to
perform larger scale data migrations in mssql. The default value
remains as one hour.

Makes the request timeout option configurable

---

lib/create-common-client.js

Several types of DDL statements in MSSQL insist on being the only thing in a batch. The MSSQL tooling uses `GO` to delimit batches in a single script so developers don't have to create multiple files for what is logically a single task or migration.
https://msdn.microsoft.com/en-us/library/ms188037.aspx
I added support for the same convention in the mssql implementation of commonClient.runQuery. I did not add support for the optional `count` parameter, as I have never seen it used anywhere, but I could add that if you think it is important.

Added support for mssql batches delimited by GO.

---

lib/create-common-client.js
readme.md
test/test-postgrator.js

Here is a working fix for port customization.
As some user probably already use the `host` property to customize postgresql's port, I've added a backward compatibility check. 
Unfortunately, can't be tested automatically, because it needs either two different instances of each server installed locally, or manual changes.
I've successfully tested it against MySQL, PostgreSQL and SQL Server locally.
I've had to change MySQL default password, because verions 5+ installer forces you to provide a value.
If you accept this PR, is it possible to publish a version soon after ? Thank you in advance.

Fix #15: allows port customizations

---

lib/create-common-client.js
package.json

- There is a change in `Buffer` in node 6+ that causes an issue with
authentication in the `pg`/`pg.js` modules.
- See https://github.com/brianc/node-postgres/issues/1018
- Which references: https://github.com/brianc/node-postgres/issues/1000
- This commit changes the pg library dependency in postgrator to the version that
contains the fix for this issue.
Basically, in node 6+, `postgrator` is intermittently failing when trying to run the migrations.  I don't know why it's intermittent, and not just an error everytime, but that seems to be what others are seeing.  `pg.js` 4.1.1 (the latest `pg.js` version) appears to still have the issue, but using `pg` 4.5.5 or later appears to fix the issue.

Fix for pg authentication issue in node 6+

---

lib/create-common-client.js

This aligns MySQL and PostgreSQL with MSSQL, and lets those databases have timestamps (eg `201606091245`) as version numbers.

MySQL and PostgreSQL now use BIGINT for version

---

lib/create-common-client.js

This lets you set ssl: true in the config to use SSL when connecting to postgres. Needed for compatibility with heroku's security policies.

Add ssl support to the pg driver

---

postgrator.js

If there is an error with updating the schema table, the callback never gets called, and the migration will hang indefinitely.
This PR will call `finishedCallback` with the error, so that the user can handle it.

Call finishedCallback when there is an error updating the schema table

---

.gitignore
postgrator.js
readme.md
test/migrations/005.do.js
test/migrations/005.undo.js
test/migrations/006.do.js
test/test-postgrator.js

At times, if we want to pass in secret environment variables that you can't check-in to your source repo, you need to be able to pass that into your SQL. Using sql files alone for migrations is sometimes too restrictive. This allows a lot of flexibility in SQL generation.
The JS module needs to export a method called generateSql() that returns a string representing the SQL. For example:
```javascript
module.exports.generateSql = function () {
return "CREATE USER transaction_user WITH PASSWORD '"+process.env.TRANSACTION_USER_PASSWORD+"'";
};
```
That's one example of where generating SQL might help. There might other instances as well. Tools such as flyway allow you to specify SQL as well as java files that do DB operations as a part of the migration. This change will allow postgrator to …

Allowing migration SQLs to be generated via a JS module

---

lib/create-common-client.js

Result object coming back from mssql returns a full object with other metadata. I believe you want result.recordset. I left in a check so previous Result object formats will work.

Updated to match new query result format

---

postgrator.js

Easiest way to expose all available migrations. Would allow `getVersions()` to return all available information about the migration scripts with one call.

Add migrations to versions object

---

postgrator.js
test/api.js

Adds a `migrationPattern` option that can be used as a glob pattern for locating migration files, rather than requiring a single directory for migrations.

Allow globs for migration file(s) location logic

---

docker-compose.yml
lib/commonClient.js
package.json
test/drivers/driverIntegration.js
test/drivers/mssql.js
test/drivers/mysql.js
test/drivers/pg.js

Adds consideration for the database/schema being operated on. This enhances support for having multiple databases/schemas being managed via postgrator on a single cluster.
For postgres, this implementation requires that the db connection info be passed in as an object, not a connection string. (that can come later - it'll require parsing the connection string to get the database name)
closes #48

Consider schema/database in ensureTable check

---

README.md
lib/commonClient.js

pass down `postGratorConfig.connectionTimeout` through to MSSQL to allow override of 15 second default

preserve connection timeout config for mssql

---

package-lock.json
package.json
postgrator.d.ts
test/api.ts
test/tsconfig.json

This PR adds a bundled type definitions file to allow consumers using TypeScript to use the package without having to manually declare the main export as `any` or take extra effort to define the types themselves.
The benefit of this is also one of developer tooling, where users of editors which integrate the TypeScript server (such as VSCode) will see hints such as this:
If you disagree with directly bundling this definition file, I can close this PR and create a new [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) respository that mirrors this one for developers who wish to install the types explicitly with `npm install @types/postgrator`.
It's up to you if you are OK with the typed being bundled here - the drawback of this is that the types definition file _must_ be …

Add TypeScript definitions

---

lib/commonClient.js
test/drivers/driverIntegration.js
test/drivers/pg.js

When using pg, create a schema when schemaTable specifies one.  `schemaversion` will work just as it does now, but `postgrator.schemaversion` will place the table in the `postgrator` schema, creating it if it doesn't exist.
I've updated the tests to use `postgrator.schemaversion`.

When using pg, create a schema when schemaTable specifies one

---

lib/commonClient.js

Firstly, nice lib!
I think a pretty common use case is people running MySQL RDS instances - which require SSL connections. Unfortunately the config for MySQL is explicitly defined and so it's currently impossible to create an SSL connection to MySQL instances.
To solve this, we can just pass the ssl config directly through to the `createConnection` call.
https://github.com/mysqljs/mysql#connection-options
Another solution might be to pass the _entire_ config block without redefining it, and thereby allow the user to have control over everything that isn't necessary for Postgrator to function correctly (if anything, they can just be overridden).

Add support for SSL connections to MySQL databases

---

lib/commonClient.js

1. Pass through `user` config prop (if `username` is empty).
- mysql expects 'user', so using the mysql driver requires the consumer to remap the prop name, which we then also remap again internally.
2. Allow `mysql2` package as a valid mysql driver. It's API compatible, more performant and uses native promises out of the box.
- Consumers of postgrator who are using mysql are probably using `mysql2` already, so forcing them to also grab the `mysql` as well is a bit annoying.
- This also necessitated moving the `utils.supportWarning` to outside of the driver creation functions, but made driver-validation rules somewhat more declarative as well.

Compatibility updates

---

postgrator.js
test/migrationFailure.js

Ends connection on encountering a failed migration. Previously the connection would be left open, leaving scripts/applications hanging. 
closes #58

End connection error

---

postgrator.js
test/api.js

Just some cleanup and small refactor to .getMigrations() in preparation of potentially expanding the types of migration scripts.
In doing so I realized there's an inconsistency in the migration.filename that is returned from postgrator.

Clean up .getMigrations()

---

README.md
lib/commonClient.js
test/drivers/pg.js

This allows the user to specify the postgres schema against which to run migrations. This is useful if, like myself, you are using schemas to create a mutli-tenanted app an your schemas are dynamically named

Add currentSchema config option for postgres

---

lib/commonClient.js

Added configuration option for domain login with sql server, I'm really not sure if this is the correct way to implement this, but adding this option allowed me to login in with my org's sql server configuration
see:
https://www.npmjs.com/package/mssql#general-same-for-all-drivers

Added MSSQL Domain option

---

postgrator.d.ts

The `currentSchema` option was introduced for PostgreSQL as per https://github.com/rickbergfalk/postgrator/commit/7c9cad93d4cea481c734f68fadf9430e30a5fd55#diff-04c6e90faac2675aa89e2176d2eec7d8R142 and https://github.com/rickbergfalk/postgrator/blob/master/CHANGELOG.md#380.
However, it is still missing from [`PostgreSQLOptions`](https://github.com/rickbergfalk/postgrator/blob/master/postgrator.d.ts#L46), so if one is using TypeScript and trying to use this option, then they can't compile their `.ts` code as `tsc` will give an error like this:
```
error TS2345: Argument of type '{ migrationDirectory: string; driver: "pg"; host: string; port: string; database: string; username: string; password: string; schemaTable: string; currentSchema: string; }' is not assignable to parameter of type …
```

Add missing currentSchema Postgres option to the type

---

README.md
postgrator.d.ts

Providing `mysql2` as a driver triggers TypeScript error. Fix attached.

MySQLOptions typings fix for mysql2

---

lib/commonClient.js

The fix allows mssql users use non-default schema for postgrator. It repeats postgresql implementation.
test result  are same for both cases with and without my changes.
not sure why 
112 passing (7s)
1 failing
getMajorVersion
1) Detects db versions
√ Fails gracefully for uninstalled module
I believe the changes is safe. You might need look why tests are bad (bad docker compose?).

fix mssql non default schema

---

docker-compose.yml

The Postgres tests were failing since the `postgres:9.6-alpine` image requires a `POSTGRES_PASSWORD` environment variable. This PR fixes the test suite by adding this environment variable.

Add POSTGRES_PASSWORD env variable in docker-compose.yml

---

.circleci/config.yml
postgrator.js
test/duplicateMigrations/001.do.sql
test/duplicateMigrations/001.undo.sql
test/duplicateMigrations/002.do.another-description.sql
test/duplicateMigrations/002.do.some-description.sql
test/duplicateMigrations/002.undo.another-description.sql
test/duplicateMigrations/002.undo.some-description.sql
test/migrationDuplicate.js

Multiple migrations with the same version number and action can occur in the following scenario:
- You switch between two development branches with conflicting migration histories
- Migrations are copied to another directory as part of a build step
This PR adds a check for this condition, erroring out if it occurs. It also bumps the CI node version to 10 so that we can use new API methods like `assert.rejects` in unit tests

Avoid multiple migrations with the same version number and action

---

postgrator.d.ts

This PR improves typings for the Postgres `ssl` option. The `ssl` option is documented here: https://node-postgres.com/features/ssl

Fix Postgres SSL typings

---

lib/PostgresClient.js

SSL connection options aren't passed through to the pg.Client if `config.connectionString` is present.
Example:-
If Postgrator is initialized like so
```js
const postgrator = new Postgrator({
driver: 'pg',
migrationDirectory: `...`,
connectionString: "postgres://...",
ssl: {
rejectUnauthorized: false
}
});
```
then the pg.Client is not initialized with the ssl options. 
Since `config.connectionString` is accepted by `pg.Client`, this change should be backward compatible.

Fix postgres ssl connection options

---

README.md

> If a change is detected, migration will stop reporting an error. 
This sounds like the migration will continue, but it will stop error reporting.
> If a change is detected, migration will stop, reporting an error. 
The migration will stop, and report an error. This is probably what was intended.

fix: "stop reporting an error" in place of "stop, reporting an error"

---

lib/Client.js
postgrator.js
test/drivers.js

Fixes #139 by checking to see if any schemaversion columns exist in the database prior to attempting to get current database version. If no columns exist, the table does not exist, and so a version does not exist.

Fix version error when schemaversion table does not exist

---

package.json

Remove the following deprecation warning printed when the module
is imported:
Automatic extension resolution of the "main" field is deprecated for ES modules.
Close #145
See also #143

Fix DEP0151 warning about ext resolution

---

lib/Client.js

Signed-off-by: Matteo Collina <hello@matteocollina.com>
In #150 I forgot to modify the datatype for the table in SQLite.
This is not functionally needed but more correct: https://www.sqlite.org/datatype3.html.

Sqlite3 use INTEGER for the version type of the metadata table
